package com.siri_hate.phone_shop_service.entity;

import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Entity class representing a phone in the phone shop.
 * Each instance of this class corresponds to a record in the "phone_shop" table in the database.
 */
@Entity
@Table(name = "phone_shop")
@Data
@NoArgsConstructor
@AllArgsConstructor
public class Phone {

    /**
     * Unique identifier for the phone entity. Automatically generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id")
    private Integer id;

    /**
     * Manufacturer of the phone.
     */
    @Column(name = "manufacturer")
    private String manufacturer;

    /**
     * Model name of the phone.
     */
    @Column(name = "model")
    private String model;

    /**
     * Storage size of the phone in gigabytes.
     */
    @Column(name = "storage_size")
    private int storageSize;

    /**
     * Color of the phone.
     */
    @Column(name = "color")
    private String color;

    /**
     * Cost of the phone in the shop.
     */
    @Column(name = "cost")
    private int cost;

    /**
     * Quantity of the phone available in the shop.
     */
    @Column(name = "quantity")
    private int quantity;

}
